language: cpp

os:
  - linux

compiler:
  # - clang # disabled clang due to missing libc++
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-5; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [[ -f /usr/bin/g++ ]]; then sudo rm /usr/bin/g++; fi
  - sudo ln /usr/bin/g++-5 /usr/bin/g++

install:
  - "cd $TRAVIS_BUILD_DIR && g++ -std=c++14 main.cpp -omain"

script:
  - "cd $TRAVIS_BUILD_DIR && ./main"
